# Generated by Django 5.0.7 on 2024-08-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='name',
        ),
    ]
