# Generated by Django 5.0.7 on 2024-10-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_song_unique_together_song_youtube_link_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'album')},
        ),
        migrations.AddField(
            model_name='song',
            name='with_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='core.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='songs', to='core.genre'),
        ),
    ]
