# Generated by Django 5.0.7 on 2025-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_song_unique_together_song_with_voice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='+', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(related_name='+', to='core.genre'),
        ),
    ]
